### ISSUE TITLE
Form fields of type hidden are disabled

### ISSUE THREAD

**Issue by LeisureLarry** [zoltan-dulac/visibleIf#4]
Hi Zoltan,

hidden fields (i.e. form tokens) are disabled. Therefore they are missing in the post data.

Greats from Germany
Jan

**Comment by zoltan-dulac** [comment]
@LeisureLarry This is something that I have taken care of.  By default, only the visible form elements are submitted to the server (this is because, as you have mentioned above, when a form element is hidden by visibleIf, its disabled attribute is set to true when the form is submitted). If developers wants to override this behavior, they can simply set the form tag’s class to visibleIf-submitInvisibleData. 

I really should put the instructions in the readme.  In the meantime, there is some documenation at my blog post about visibleIf:

http://www.useragentman.com/blog/2010/06/20/visibleif-html5-custom-data-attributes-with-javascript-make-dynamic-interactive-forms/

Hope this helps.
Z.

**Comment by LeisureLarry** [comment]
Yes, invisible form fields which are hidden by visibleIf shouldn't be submitted to the server. But your code influences input type="hidden" fields, which it shouldn't. They are invisible by its type and shouldn't be changed at all. My fork solves this problem using the new isTypeHidden check.

Greats form Germany
Jan
